version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    logging:
      driver: "json-file"
      options:
          max-file: "3"
          max-size: "1m"
