version: '3'

volumes:
  gitlab-runner-config:
    name: gitlab-runner-config

services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:v14.10.0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
    logging:
      driver: "json-file"
      options:
          max-file: "3"
          max-size: "10M"

